Repository minhaj-313/Portfolio-1, pull requests merged in 2022-10, with the labels that each got.

#10 Issue#6: Fixed typos and grammar in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 Code for footer and some customizations added
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#13 Updated style.css
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#14 Remove width to center icons
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#15 portfolio/8
  footer.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#16 Improved services UI
  index.html
  services.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#20 fixed social icons on footer
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#34 Update footer, issue number #27
  footer.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 Revamped navigation toggle
  footer.css
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#49 #39 : Hamburger Not working in some pages
  contact.html
  intro.html
  services.html
Labels: hacktoberfest, hacktoberfest-accepted

#50 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#51 hover effect on side navbars
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#52 Updated main styles and footer styles - Portfolio/42 - d7321016dec040023549f4e24014b59bd0175923
  footer.css
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#53 Adding social links linktree
  index.html
  linktree.html
  styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#54 hactoberfest2022
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#56 intro page UI improved
  .vscode/settings.json
  changes.css
  intro.html
Labels: hacktoberfest, hacktoberfest-accepted

#59 fixed routing issue and fixed bugs
  blog.html
  contact.html
  index.html
  intro.html
Labels: hacktoberfest, hacktoberfest-accepted

#61 Added linktree page link to sidebar on every page
  blog.html
  contact.html
  intro.html
  services.html
Labels: hacktoberfest, hacktoberfest-accepted

#62 Updated styling (changes.css) for intro.html #17
  changes.css
Labels: hacktoberfest-accepted

#64 Made Contact Me Section better
  contact.html
  style.css
Labels: hacktoberfest-accepted

#67 < Made a preloader >
  index.html
  style.css
Labels: hacktoberfest-accepted

#70 Added Form validation for all attributes
  Thankyou.html
  contact.html
  style.css
Labels: hacktoberfest-accepted

#72 Hamburger menu icon solved
  blog.html
  contact.html
  intro.html
  services.html
Labels: hacktoberfest-accepted

#73 Enhanced UI with buttons
  style.css
Labels: hacktoberfest-accepted

#75 issue 74, improved contact page
  contact.html
  style.css
Labels: hacktoberfest-accepted

#76 Create Portfolio Page
  images/image2.jpg
  images/image3.jpg
  images/image4.jpg
  portfolio.css
  portfolio.html
  portfolio.js
Labels: hacktoberfest-accepted

#79 Update services.html
  services.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#82 #80 issue : Contact form UI updated
  contact.html
  images/contact-bg-img.jpeg
  style.css
Labels: hacktoberfest-accepted

#83 Pretty colors n Additional Words have been added by me
  footer.css
  index.html
  intro.html
  style.css
Labels: hacktoberfest-accepted

#87 Improved the navbar
  changes.css
  style.css
Labels: hacktoberfest-accepted

#89 Updated Blogs page
  blog.html
Labels: hacktoberfest-accepted

#91 Added a template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: hacktoberfest-accepted

#93 Added pipes in footer quicklinks
  .vscode/settings.json
  footer.css
  index.html
Labels: hacktoberfest-accepted

#92 Styled the page
  contact.css
  contact.html
Labels: hacktoberfest-accepted

#94 Fixed the responsiveness of the header
  style.css
Labels: hacktoberfest-accepted
